### PR TITLE
Accept playlist with different url lengths

### PR DESCRIPTION
**Pull request by raulpy271**
To verify if is a playlist the app use URL to parse the query params, with it, the app can check if the  `list` parameter has present if it has then it's a playlist.

### CODE REVIEW

**Comment by raulpy271** [comment]
@amantiwari1,

Now all urls of the file [url.txt](https://github.com/amantiwari1/youtube-GUI/blob/main/url.txt) are working for me. Check it

**Comment by raulpy271** [comment]
Hi @amantiwari1, did you checked the url's of the file?

**Comment by amantiwari1** [comment]
@raulpy271 

One Video link is always 11 chars

Different Playlist is not always same chars

so we should stay this code regex 
```js
let oneVideoUrl = (
            /^https:\/\/www\.youtube\.com\/watch\?v=\S{11}\s*$/
        )
```

so lets ignore One video url 

lets focus on playlist 

the question is how to verify playlist url?

**Comment by amantiwari1** [comment]
> Hi @amantiwari1, did you checked the url's of the file?

yes i have checked it and all link working great!

**Comment by raulpy271** [comment]
That's okay, I'll agree with you, we can assume that the url will always have 11 chars. That's can be a problem in the future, the yt can change it, but I think that it is a rare case

**Comment by amantiwari1** [comment]
try it in one video
```js
let id = parseInt(params.get('v'));
if ( id === 11 ) {
  return true
 }
```

In playlist
we have to  figure out how to playlist url  is working or not for example ->

`https://www.youtube.com/playlist?list=PLu0W_9lII9agICnT8t4iYVSZ3eykIAOME` is working url then it should return true

`https://www.youtube.com/playlist?list=PLu0W_9lII9agICnT8t4iYVSZ3eykIAOM3` is not working url then it should return false

**Comment by raulpy271** [comment]
> the question is how to verify playlist url?

In this #9 issue, I said that even correct video or playlist url no necessarily has a video that represent it. So, we need to add a test in the backend to check if the video exists, it should check videos or playlist

**Comment by raulpy271** [comment]
> we have to figure out how to playlist url is working or not for example

I think that we can't check it in the frontend, we need to access youtube_dl to check, I suspect that the playlist don't have a pattern to represent it, even if we figure out how to check it we need to send a request to youtube to have sure that the video exists.

**Comment by raulpy271** [comment]
I will check how to do it in the backend

**Comment by raulpy271** [comment]
> ```js
> let id = params.get('v');
> if ( id === 11 ) {
>   return true
>  }
> ```

I added it.

**Comment by raulpy271** [comment]
Hey @amantiwari1 

With these commits, the backend can return an error object when the user types a sintaticly correct url but the video doesn't exist, so the front can read this error and show a url error to the user.

These work to single videos, I will use the same idea to fix the problem when the link is a valid playlist but the playlist doesn't exist. 

Perhaps I fix it tomorrow, but while not you can test my changes.

**Comment by amantiwari1** [comment]
Great Work!!!

**Comment by amantiwari1** [comment]
I fixed it and able to show playlist doesn't exist warning to user. Please check it

**Comment by amantiwari1** [comment]
> Why you changed it? Did you want to avoid errors when the message is undefined?
because without internet. result ` cant defined 'error' of the null  ` in GUI
yes, in offline 
try it without internet!

**Comment by raulpy271** [comment]
> because without internet. result `cant defined 'error' of the null ` in GUI
> yes, in offline
> try it without internet!

**Comment by raulpy271** [comment]
that's okay, soon I test it

**Review by amantiwari1 — APPROVED** [review]

**Comment by raulpy271** [comment]
Hi, @amantiwari1,

With this commit 317ba58 we can send errors from main file. great work!

**Comment by raulpy271** [comment]
You forgot to add a try/catch block in the function that get playlist details, I added it. 

Now all links are working, review it

**Review by amantiwari1 — APPROVED** [review]

**Comment by amantiwari1** [comment]
I am thinking `Warning` is not good so I am gonna remove it and will add `isError`, simply say `Please enter a valid YouTube URL` where Warning has been removed

**Comment by amantiwari1** [comment]
what do you think?

> I am thinking `Warning` is not good so I am gonna remove it and will add `isError`, simply say `Please enter a valid YouTube URL` where Warning has been removed

what do you think?

**Comment by raulpy271** [comment]
I agree, that's no problem

**Comment by raulpy271** [comment]
Go ahead and do it, I'm watching lessons now

**Comment by amantiwari1** [comment]
Got remove fully warning and added `is_not_connected` function  and 
finally if  url is wrong and correct 11 char then 
it return `Please enter a valid YouTube URL`  
else if is_not_connected and url is correct is false then
 it return `Please check your internet and try again`

I have done all above 

@raulpy271

**Review by raulpy271 — COMMENTED** [review]
Great work @amantiwari1,

For me, we can merge it

**Review by amantiwari1 — APPROVED** [review]

**Pull request merged**
